Repository ibnue/readygo-tpo, pull requests merged in 2022-06, with the labels that each got.

#18 feat/홈UI
  tpo-client/public/index.html
  tpo-client/src/App.tsx
  tpo-client/src/assets/ic-clock.png
  tpo-client/src/assets/ic-division-gray.png
  tpo-client/src/assets/ic-division-white.png
  tpo-client/src/assets/ic-location.png
  tpo-client/src/assets/img-dummy-card.png
  tpo-client/src/assets/logo.png
  tpo-client/src/components/Main/Home.tsx
Labels: frontend, feature

#28 feat: 사용자 CRUD 및 구글 로그인 기능 구현
  tpo-server/.gitignore
  tpo-server/build.gradle
  tpo-server/src/main/java/com/readygo/tpo/TpoApplication.java
  tpo-server/src/main/java/com/readygo/tpo/common/domain/BaseTimeEntity.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/ErrorResponse.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/GlobalExceptionHandler.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/exception/AuthException.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/exception/BusinessException.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/exception/EntityNotFoundException.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/exception/ErrorCode.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/exception/InvalidValueException.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/AppProperties.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/CurrentUser.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/CustomUserDetailsService.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/RestAuthenticationEntryPoint.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/SecurityConfig.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/TokenAuthenticationFilter.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/TokenProvider.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/UserPrincipal.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/oauth2/CustomOAuth2UserService.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/oauth2/OAuth2Attributes.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/oauth2/OAuth2SuccessHandler.java
  tpo-server/src/main/java/com/readygo/tpo/user/api/UserApiController.java
  tpo-server/src/main/java/com/readygo/tpo/user/application/UserService.java
  tpo-server/src/main/java/com/readygo/tpo/user/dao/UserRepository.java
  tpo-server/src/main/java/com/readygo/tpo/user/domain/Gender.java
  tpo-server/src/main/java/com/readygo/tpo/user/domain/Role.java
  tpo-server/src/main/java/com/readygo/tpo/user/domain/StyleCategory.java
  tpo-server/src/main/java/com/readygo/tpo/user/domain/User.java
  tpo-server/src/main/java/com/readygo/tpo/user/dto/UserRegisterRequest.java
  tpo-server/src/main/java/com/readygo/tpo/user/dto/UserResponse.java
  tpo-server/src/main/java/com/readygo/tpo/user/dto/UserUpdateRequest.java
  tpo-server/src/main/java/com/readygo/tpo/util/CookieUtils.java
  tpo-server/src/main/resources/application.properties
  tpo-server/src/main/resources/application.yml
  tpo-server/src/test/java/com/readygo/tpo/common/error/GlobalExceptionHandlerTest.java
  tpo-server/src/test/java/com/readygo/tpo/user/dao/UserRepositoryTest.java
Labels: backend, feature

#30 feat: 날씨 조회 기능 구현
  tpo-server/.gitignore
  tpo-server/build.gradle
  tpo-server/src/main/java/com/readygo/tpo/config/security/WebMvcConfig.java
  tpo-server/src/main/java/com/readygo/tpo/weather/ApiKey.java
  tpo-server/src/main/java/com/readygo/tpo/weather/api/WeatherApiController.java
  tpo-server/src/main/java/com/readygo/tpo/weather/application/WeatherService.java
  tpo-server/src/main/java/com/readygo/tpo/weather/domain/RainType.java
  tpo-server/src/main/java/com/readygo/tpo/weather/domain/SkyType.java
  tpo-server/src/main/java/com/readygo/tpo/weather/dto/DailyFcst.java
  tpo-server/src/main/java/com/readygo/tpo/weather/dto/HourTmp.java
  tpo-server/src/main/java/com/readygo/tpo/weather/dto/HourlyFcst.java
  tpo-server/src/main/java/com/readygo/tpo/weather/dto/WeatherRequest.java
  tpo-server/src/main/java/com/readygo/tpo/weather/dto/WeatherResponse.java
  tpo-server/src/main/resources/application.yml
Labels: backend, feature

#35 refactor: 사용자 기능 버그 수정 및 리팩토링
  tpo-server/src/main/java/com/readygo/tpo/TpoApplication.java
  tpo-server/src/main/java/com/readygo/tpo/config/JpaConfig.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/TokenAuthenticationFilter.java
  tpo-server/src/main/java/com/readygo/tpo/config/security/oauth2/OAuth2Attributes.java
  tpo-server/src/main/java/com/readygo/tpo/user/application/UserService.java
  tpo-server/src/main/java/com/readygo/tpo/user/domain/User.java
  tpo-server/src/main/java/com/readygo/tpo/user/dto/UserRegisterRequest.java
  tpo-server/src/main/java/com/readygo/tpo/user/dto/UserUpdateRequest.java
  tpo-server/src/main/resources/application.yml
  tpo-server/src/test/java/com/readygo/tpo/user/dao/UserRepositoryTest.java
Labels: bug, backend, refactor

#39 refactor: 공통 응답 포맷 적용
  tpo-server/src/main/java/com/readygo/tpo/common/ApiResponse.java
  tpo-server/src/main/java/com/readygo/tpo/common/ResponseMessage.java
  tpo-server/src/main/java/com/readygo/tpo/common/error/ErrorResponse.java
  tpo-server/src/main/java/com/readygo/tpo/user/api/UserApiController.java
  tpo-server/src/main/java/com/readygo/tpo/weather/api/WeatherApiController.java
Labels: backend, refactor
